version: "3"
services:
  web:
    hostname: notes
    build: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./app/:/app/
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_USER=DB_USER
      - POSTGRES_PASSWORD=DB_PASSWORD
      - POSTGRES_DB=DB_NAME
    expose:
      - 5432